[workspace]
resolver = "2"
members = [
    "workflow/deployer-workflow/impl-flyio",
    "webhook/healthcheck",
]

[workspace.package]
version = "0.1.0"
license = "MIT"
authors = ["Project Developers"]
edition = "2024"
repository = "TBD"
rust-version = "1.90.0"

[workspace.dependencies]
anyhow = "1.0"
assert_matches = "1.5.0"
const_format = "0.2.35"
derive_more = { version = "2.1.0", features = ["debug"] }
hashbrown = "0.16.1"
insta = "1.44.3"
serde = { version = "1.0", features = ["derive"] }
toml = "0.9"
wit-bindgen = "0.50.0"
wit-bindgen-rust = "0.50.0"
wit-parser = "0.243.0"
wstd = "0.6.3"

[profile.release]
opt-level = "z"
lto = true
overflow-checks = true

[profile.release_webhook]
inherits = "release"
strip = "debuginfo"

[profile.release_workflow]
inherits = "release"
debug = "line-tables-only"
