api.listening_addr = "127.0.0.1:5005"
webui.listening_addr = "127.0.0.1:8080"

database.postgres.host =     "${POSTGRES_HOST}"
database.postgres.user =     "${POSTGRES_USER}"
database.postgres.password = "${POSTGRES_PASSWORD}"
database.postgres.db_name =  "${POSTGRES_DATABASE}"
database.postgres.provision_policy = "auto"

[log.file]
enabled = true
target = true
level="info"
directory = "."
prefix = "obelisk.log" # File name prefix

[[activity_wasm]]
name = "activity_fly_http"
location.oci = "docker.io/getobelisk/components_fly_activity_fly_http:2026-01-13-1@sha256:7b39b252793821b0b7a1cfb4c330fa41c869a8895cfd0ee69c9a9b7e2d3d1b9d"
exec.lock_expiry.seconds = 15
env_vars = ["FLY_API_TOKEN"]
forward_stdout = "stderr"
forward_stderr = "stderr"
max_retries = 6

# HTTP Client for health checking.
[[activity_wasm]]
name = "activity_http_generic"
location.oci = "docker.io/getobelisk/components_http_activity_http_generic:2026-01-13@sha256:f64b64aa176224645a21d583312ad1e832afae57af138998711771c4411e3b3e"
exec.lock_expiry.seconds = 5

[[activity_wasm]]
name = "activity_obelisk_client"
location.oci = "docker.io/getobelisk/components_obelisk_activity_obelisk_client_http:2026-01-10@sha256:ca99fa1f0b08d1883784baff2966e07abe36b450b63d8deac25f8abf8cecd0ce"
forward_stdout = "stderr"
forward_stderr = "stderr"

[[workflow]]
name = "obelisk_deployer_flyio"
location.path = "${OBELISK_TOML_DIR}/target/wasm32-unknown-unknown/release_workflow/obelisk_deployer_flyio.wasm"
backtrace.sources = {
    ".../src/lib.rs" = "${OBELISK_TOML_DIR}/workflow/deployer-workflow/src/lib.rs",
    ".../src/testing.rs" = "${OBELISK_TOML_DIR}/workflow/deployer-workflow/src/testing.rs",
    ".../src/toml.rs" = "${OBELISK_TOML_DIR}/workflow/deployer-workflow/src/toml.rs",
}
backtrace.ignore_component_digest = true

[[http_server]]
name = "webhook_server"
listening_addr = "0.0.0.0:9090"
