api.listening_addr = "127.0.0.1:5005"
webui.listening_addr = "127.0.0.1:8080"

log.stdout.enabled = true

[[activity_wasm]]
name = "activity_fly_http"
location.oci = "docker.io/getobelisk/components_flyio_activity_fly_http:2025-10-02@sha256:e8102a027a7107b2c8cf0aea5a4bcacb1c72bfb785c95b9a791c7d9ad01ff653"
exec.lock_expiry.seconds = 15
env_vars = ["FLY_API_TOKEN"]
forward_stdout = "stderr"
forward_stderr = "stderr"

[[activity_wasm]]
name = "http_activity"
location.oci = "docker.io/getobelisk/test_programs_http_get_activity:2025-09-28@sha256:8131d9cafbdf06dbaf7a3b4e629791c9cf3dc1553df9418b34f25ab900b72929"
exec.lock_expiry.seconds = 5
forward_stdout = "stderr"
forward_stderr = "stderr"

[[webhook_endpoint]]
name = "webhook_fly_secrets_updater"
location.oci = "docker.io/getobelisk/components_flyio_webhook_fly_secrets_updater:2025-10-02@sha256:d8da4742aeb09a09b95eed70b28558fea7e75b401e609da17179ff1201b91997"
http_server = "webhook_server"
routes = [{ methods = ["POST"], route = "/" }]
env_vars = ["FLY_API_TOKEN"]
forward_stdout = "stderr"
forward_stderr = "stderr"

[[workflow]]
name = "obelisk_deployer_flyio"
location.oci = "docker.io/getobelisk/components_flyio_obelisk_deployer_flyio:2025-10-02@sha256:f4d6796b24587d148752e8d280cccd61cb7fbbbf91a032042bb9aaed65666329"
backtrace.sources = { "${OBELISK_TOML_DIR}/workflow/deployer-workflow/impl-flyio/src/lib.rs" = "${OBELISK_TOML_DIR}/workflow/deployer-workflow/impl-flyio/src/lib.rs" }

# This webhook is here only for `push-components.sh`
[[webhook_endpoint]]
name = "webhook_healthcheck"
location.oci = "docker.io/getobelisk/components_flyio_webhook_healthcheck:2025-10-02@sha256:63dc41cc0d4201cfff84bb6963993e2aeca3eb8c7d42e6a095c15d424950609b"
http_server = "webhook_server"
routes = ["/obeliskhealthcheck"]

[[http_server]]
name = "webhook_server"
listening_addr = "0.0.0.0:9090"
