api.listening_addr = "127.0.0.1:5005"
webui.listening_addr = "127.0.0.1:8080"

log.stdout.enabled = true

[[activity_wasm]]
name = "activity_fly_http"
location.oci = "docker.io/getobelisk/components_flyio_activity_fly_http:2025-09-30-1@sha256:ab5c2c14be40b9b6702a4072c24615bf7bc0e42c82806c284810a3c9682f0f91"
exec.lock_expiry.seconds = 15
env_vars = ["FLY_API_TOKEN"]
forward_stdout = "stderr"
forward_stderr = "stderr"

[[activity_wasm]]
name = "http_activity"
location.oci = "docker.io/getobelisk/test_programs_http_get_activity:2025-09-28@sha256:8131d9cafbdf06dbaf7a3b4e629791c9cf3dc1553df9418b34f25ab900b72929"
exec.lock_expiry.seconds = 5
forward_stdout = "stderr"
forward_stderr = "stderr"

[[webhook_endpoint]]
name = "webhook_fly_secrets_updater"
location.oci = "docker.io/getobelisk/components_flyio_webhook_fly_secrets_updater:2025-09-30-1@sha256:3a4feb1bd87d6eb7028f8a4c6163730680ed3659714e5a762d86e863275a72bb"
http_server = "webhook_server"
routes = [{ methods = ["POST"], route = "/" }]
env_vars = ["FLY_API_TOKEN"]
forward_stdout = "stderr"
forward_stderr = "stderr"

[[workflow]]
name = "obelisk_deployer_flyio"
location.oci = "docker.io/getobelisk/components_flyio_obelisk_deployer_flyio:2025-10-01@sha256:38e3b813a8f20666e0310cd17a9bcf4649cb93140ca30b26c9c17c38e0de8980"
backtrace.sources = { "${OBELISK_TOML_DIR}/workflow/deployer-workflow/impl-flyio/src/lib.rs" = "${OBELISK_TOML_DIR}/workflow/deployer-workflow/impl-flyio/src/lib.rs" }

# This webhook is here only for `push-components.sh`
[[webhook_endpoint]]
name = "webhook_healthcheck"
location.oci = "docker.io/getobelisk/components_flyio_webhook_healthcheck:2025-10-01@sha256:6fbc11b80b441ae6e642327b1ec0ceba85b2868d85dbce2d99d0d7b14a525c8c"
http_server = "webhook_server"
routes = ["/obeliskhealthcheck"]

[[http_server]]
name = "webhook_server"
listening_addr = "0.0.0.0:9090"
