api.listening_addr = "127.0.0.1:5005"
webui.listening_addr = "127.0.0.1:8080"

log.stdout.enabled = true

[[activity_wasm]]
name = "activity_fly_http"
location.oci = "docker.io/getobelisk/components_fly_activity_fly_http:2026-01-10@sha256:4985d2a91d1edcb2312617be37ebb8a4599c886e714b47227c69dbd15c51b2f9"
exec.lock_expiry.seconds = 15
env_vars = ["FLY_API_TOKEN"]
forward_stdout = "stderr"
forward_stderr = "stderr"
max_retries = 6

[[activity_wasm]]
name = "http_activity"
location.oci = "docker.io/getobelisk/test_programs_http_get_activity:2025-09-28@sha256:8131d9cafbdf06dbaf7a3b4e629791c9cf3dc1553df9418b34f25ab900b72929"
exec.lock_expiry.seconds = 5
forward_stdout = "stderr"
forward_stderr = "stderr"

[[activity_wasm]]
name = "activity_obelisk_client"
location.oci = "docker.io/getobelisk/components_obelisk_activity_obelisk_client_http:2026-01-10@sha256:ca99fa1f0b08d1883784baff2966e07abe36b450b63d8deac25f8abf8cecd0ce"
forward_stdout = "stderr"
forward_stderr = "stderr"

[[workflow]]
name = "obelisk_deployer_flyio"
location.oci = "docker.io/getobelisk/components_flyio_obelisk_deployer_flyio:2026-01-10@sha256:b6fecac90b5ca7d9e585a3142416446e1c060714cf7d2843b987d8cf51f1c5eb"
backtrace.sources = {
    ".../src/lib.rs" = "${OBELISK_TOML_DIR}/workflow/deployer-workflow/src/lib.rs",
    ".../src/testing.rs" = "${OBELISK_TOML_DIR}/workflow/deployer-workflow/src/testing.rs",
    ".../src/toml.rs" = "${OBELISK_TOML_DIR}/workflow/deployer-workflow/src/toml.rs",
}

# This webhook is here only for `push-components.sh`
[[webhook_endpoint]]
name = "webhook_healthcheck"
location.oci = "docker.io/getobelisk/components_flyio_webhook_healthcheck:2026-01-10@sha256:e6f6823eb3ecd406f1ccb69c7ffd47aac6987f7c963529884b34f35a4488f0c0"
http_server = "webhook_server"
routes = ["/obeliskhealthcheck"]

[[http_server]]
name = "webhook_server"
listening_addr = "0.0.0.0:9090"
