api.listening_addr = "127.0.0.1:5005"
webui.listening_addr = "127.0.0.1:8080"

log.stdout.enabled = true

[[activity_wasm]]
name = "activity_fly_http"
location.oci = "docker.io/getobelisk/components_flyio_activity_fly_http:2025-10-05@sha256:fc19825d246fae8110f0473a505bf1da727086832bb0820653ec36e940822024"
exec.lock_expiry.seconds = 15
env_vars = ["FLY_API_TOKEN"]
forward_stdout = "stderr"
forward_stderr = "stderr"
max_retries = 9

[[activity_wasm]]
name = "http_activity"
location.oci = "docker.io/getobelisk/test_programs_http_get_activity:2025-09-28@sha256:8131d9cafbdf06dbaf7a3b4e629791c9cf3dc1553df9418b34f25ab900b72929"
exec.lock_expiry.seconds = 5
forward_stdout = "stderr"
forward_stderr = "stderr"

[[webhook_endpoint]]
name = "webhook_fly_secrets_updater"
location.oci = "docker.io/getobelisk/components_flyio_webhook_fly_secrets_updater:2025-10-05@sha256:3190ff8d059210d29b1a58f0fc509015360bb0e6bf34deba23b9c5a8c816c8cc"
http_server = "webhook_server"
routes = [{ methods = ["POST"], route = "/" }]
env_vars = ["FLY_API_TOKEN"]
forward_stdout = "stderr"
forward_stderr = "stderr"

[[workflow]]
name = "obelisk_deployer_flyio"
location.oci = "docker.io/getobelisk/components_flyio_obelisk_deployer_flyio:2025-10-05@sha256:29a081ec850926f7471ad96af66440b62c9a6b64f803bb5c8062467d32c9930a"
backtrace.sources = { ".../src/lib.rs" = "${OBELISK_TOML_DIR}/workflow/deployer-workflow/impl-flyio/src/lib.rs" }

# This webhook is here only for `push-components.sh`
[[webhook_endpoint]]
name = "webhook_healthcheck"
location.oci = "docker.io/getobelisk/components_flyio_webhook_healthcheck:2025-10-05@sha256:f0119d7d24fe0d9d2f5c02920338d9551802fae666d62d5f5919eab26293febe"
http_server = "webhook_server"
routes = ["/obeliskhealthcheck"]

[[http_server]]
name = "webhook_server"
listening_addr = "0.0.0.0:9090"
