api.listening_addr = "127.0.0.1:5005"
webui.listening_addr = "127.0.0.1:8080"

log.stdout.enabled = true

[[activity_wasm]]
name = "activity_fly_http"
location.oci = "docker.io/getobelisk/components_flyio_activity_fly_http:2025-09-30@sha256:4c8501b794f093a965c3a5e1274feb49ac69aa6d3e0a18dd829050524d7fe5af"
exec.lock_expiry.seconds = 15
env_vars = ["FLY_API_TOKEN"]
forward_stdout = "stderr"
forward_stderr = "stderr"

[[webhook_endpoint]]
name = "webhook_fly_secrets_updater"
location.oci = "docker.io/getobelisk/components_flyio_webhook_fly_secrets_updater:2025-09-30@sha256:360ba2106bddbb3bd14785ccda7248446d70b3b5b308e8ee1366eb60b9248f08"
http_server = "webhook_server"
routes = [{ methods = ["POST"], route = "/" }]
env_vars = ["FLY_API_TOKEN"]
forward_stdout = "stderr"
forward_stderr = "stderr"

[[workflow]]
name = "deployer_flyio"
location.path = "${OBELISK_TOML_DIR}/target/wasm32-unknown-unknown/release/obelisk_deployer_flyio.wasm"
backtrace.sources = { "${OBELISK_TOML_DIR}/workflow/deployer-workflow/impl-flyio/src/lib.rs" = "${OBELISK_TOML_DIR}/workflow/deployer-workflow/impl-flyio/src/lib.rs" }

[[http_server]]
name = "webhook_server"
listening_addr = "0.0.0.0:9090"
