package obelisk-flyio:workflow@1.0.0-beta;

interface workflow {
    use types.{obelisk-config, app-init-modify-error, app-init-error};

    /// Create the Fly.io app.
    /// Allocate an IP address.
    /// Create and prepare a volume.
    /// Wait until secrets are populated.
    /// Start the final VM.
    app-init-no-cleanup: func(
        org-slug: string,
        app-name: string,
        config: obelisk-config,
        sleep-between-retries-seconds: u32,
        max-healthcheck-attempts: u32,
        ) -> result<_, app-init-modify-error>;

    /// Wraps `app-init-no-cleanup` with a cleanup routine.
    /// If an error occurs during app configuration
    /// the app is deleted, leaving the state as it was before this function was called.
    /// If the cleanup fails as well `cleanup-error` is raised.
    app-init: func(
        org-slug: string,
        app-name: string,
        config: obelisk-config,
        sleep-between-retries-seconds: u32,
        max-healthcheck-attempts: u32,
        ) -> result<_, app-init-error>;
}

world exports {
    export workflow;
}
