[profile.ci-test]
failure-output = "immediate"
fail-fast = false
status-level = "all"
slow-timeout = { period = "10s", terminate-after = 4 }
junit.path = "junit.xml"
junit.report-name = "ci-test"
junit.store-success-output = true
junit.store-failure-output = true
